/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CDC Backend API
 * API description
 * OpenAPI spec version: 1.0
 */

export interface CreatePostDto {
    title: string;
    /**
     * The content of the post, up to 1000 characters
     * @maxLength 1000
     * @nullable
     */
    content?: string | null;
    /** @nullable */
    published?: boolean | null;
}
