/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CDC Backend API
 * API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateConversationDto {
    title?: string;
    /** @nullable */
    description?: string | null;
}
