/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CDC Backend API
 * API description
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
    id: number;
    email: string;
    /** @nullable */
    name: string | null;
}
