name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: asia-southeast2
          REPOSITORY: cdc-frontend-docker
          IMAGE_NAME: frontend
        run: |
          gcloud builds submit --tag asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA .

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: asia-southeast2
          REPOSITORY: cdc-frontend-docker
          IMAGE_NAME: frontend
          SERVICE_NAME: cdc-frontend-image
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 3000