name: Deploy to Production via Cloudflare Tunnel

# This workflow will not run automatically because we don't have the domain name and infrastructure set up.
# Uncomment the following lines to enable it when ready.

#on:
#  push:
#    branches:
#      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: dockerhub_username/cdc-quang-ninh-frontend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/project/on/server
            
            echo "TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }}" > .env
            
            docker pull dockerhub_username/cdc-quang-ninh-frontend:latest
            
            docker pull cloudflare/cloudflared:latest

            docker-compose up -d --force-recreate
            
            docker image prune -f